version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: production_nginx
    ports:
      - 80:80
      - 443:443

  api:
    image: node:alpine
    # command: ["npm", "run", "start"]
    # command: ["sleep", "10000"]
    command: ["npm", "run", "start"]
#    command: ["ls", "-lah"]
    working_dir: /code/server
    volumes:
      - ./server:/code/server
    ports:
      - 3000:3000

  react-dev:
    image: node:alpine
    command: ["npm", "run", "start"]
    # command: ["ls", "-lah", "/code/client"]
#    command: ["ls", "-lah"]
    working_dir: /code/client
    volumes:
      - ./client:/code/client
    ports:
      - 3001:3000
