version: '3'

services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443

  # Express API service
  api:
    image: node:14-alpine
    volumes:
      - ./server:/code
    ports:
      - 3000:3000
    
  # create-react-app's "serve" thing.
  react-dev:
    image: node:14-alpine
    volumes:
      - ./client:/code
    ports:
      - 3001:3000